[2024-11-05T20:25:50.012+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-05T20:25:50.025+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: backup_files_dag.backup_files manual__2024-11-05T20:25:46.983253+00:00 [queued]>
[2024-11-05T20:25:50.030+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: backup_files_dag.backup_files manual__2024-11-05T20:25:46.983253+00:00 [queued]>
[2024-11-05T20:25:50.031+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-05T20:25:50.042+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): backup_files> on 2024-11-05 20:25:46.983253+00:00
[2024-11-05T20:25:50.047+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=74) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-05T20:25:50.049+0000] {standard_task_runner.py:72} INFO - Started process 76 to run task
[2024-11-05T20:25:50.049+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'backup_files_dag', 'backup_files', 'manual__2024-11-05T20:25:46.983253+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/backup_files_dag.py', '--cfg-path', '/tmp/tmp5hqgbykg']
[2024-11-05T20:25:50.050+0000] {standard_task_runner.py:105} INFO - Job 97: Subtask backup_files
[2024-11-05T20:25:50.110+0000] {task_command.py:467} INFO - Running <TaskInstance: backup_files_dag.backup_files manual__2024-11-05T20:25:46.983253+00:00 [running]> on host 21d07c241839
[2024-11-05T20:25:50.207+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='backup_files_dag' AIRFLOW_CTX_TASK_ID='backup_files' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T20:25:46.983253+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T20:25:46.983253+00:00'
[2024-11-05T20:25:50.209+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-05T20:25:50.210+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-05T20:25:50.210+0000] {logging_mixin.py:190} INFO - Current task name:backup_files state:running start_date:2024-11-05 20:25:50.025820+00:00
[2024-11-05T20:25:50.211+0000] {logging_mixin.py:190} INFO - Dag name:backup_files_dag and current dag run status:running
[2024-11-05T20:25:50.212+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-05T20:25:50.213+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-05T20:25:50.214+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cp -r /opt/***/source* /opt/***/backup']
[2024-11-05T20:25:50.225+0000] {subprocess.py:86} INFO - Output:
[2024-11-05T20:25:55.887+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-05T20:25:55.909+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-05T20:25:55.910+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=backup_files_dag, task_id=backup_files, run_id=manual__2024-11-05T20:25:46.983253+00:00, execution_date=20241105T202546, start_date=20241105T202550, end_date=20241105T202555
[2024-11-05T20:25:55.921+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-05T20:25:55.923+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-05T20:25:55.924+0000] {logging_mixin.py:190} INFO - Dag name:backup_files_dag queued_at:2024-11-05 20:25:47.039737+00:00
[2024-11-05T20:25:55.925+0000] {logging_mixin.py:190} INFO - Task hostname:21d07c241839 operator:BashOperator
[2024-11-05T20:25:55.971+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-05T20:25:56.018+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-05T20:25:56.024+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
