[2024-11-04T20:27:36.032+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-04T20:27:36.044+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: backup_files_dag.backup_files manual__2024-11-04T20:27:33.765985+00:00 [queued]>
[2024-11-04T20:27:36.051+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: backup_files_dag.backup_files manual__2024-11-04T20:27:33.765985+00:00 [queued]>
[2024-11-04T20:27:36.052+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-04T20:27:36.061+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): backup_files> on 2024-11-04 20:27:33.765985+00:00
[2024-11-04T20:27:36.069+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=67) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-04T20:27:36.072+0000] {standard_task_runner.py:72} INFO - Started process 69 to run task
[2024-11-04T20:27:36.071+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'backup_files_dag', 'backup_files', 'manual__2024-11-04T20:27:33.765985+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/backup_files_dag.py', '--cfg-path', '/tmp/tmp0zz3827y']
[2024-11-04T20:27:36.073+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask backup_files
[2024-11-04T20:27:36.112+0000] {task_command.py:467} INFO - Running <TaskInstance: backup_files_dag.backup_files manual__2024-11-04T20:27:33.765985+00:00 [running]> on host 1488fd0dc185
[2024-11-04T20:27:36.171+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='backup_files_dag' AIRFLOW_CTX_TASK_ID='backup_files' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T20:27:33.765985+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-04T20:27:33.765985+00:00'
[2024-11-04T20:27:36.173+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-04T20:27:36.174+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-04T20:27:36.175+0000] {logging_mixin.py:190} INFO - Current task name:backup_files state:running start_date:2024-11-04 20:27:36.045685+00:00
[2024-11-04T20:27:36.176+0000] {logging_mixin.py:190} INFO - Dag name:backup_files_dag and current dag run status:running
[2024-11-04T20:27:36.177+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-04T20:27:36.178+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-04T20:27:36.180+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cp -r /opt/***/source* /opt/***/backup']
[2024-11-04T20:27:36.188+0000] {subprocess.py:86} INFO - Output:
[2024-11-04T20:27:36.210+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-04T20:27:36.230+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-04T20:27:36.231+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=backup_files_dag, task_id=backup_files, run_id=manual__2024-11-04T20:27:33.765985+00:00, execution_date=20241104T202733, start_date=20241104T202736, end_date=20241104T202736
[2024-11-04T20:27:36.240+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-04T20:27:36.240+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-04T20:27:36.240+0000] {logging_mixin.py:190} INFO - Dag name:backup_files_dag queued_at:2024-11-04 20:27:33.794254+00:00
[2024-11-04T20:27:36.241+0000] {logging_mixin.py:190} INFO - Task hostname:1488fd0dc185 operator:BashOperator
[2024-11-04T20:27:36.247+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-04T20:27:36.261+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-04T20:27:36.263+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
