[2024-11-06T17:54:32.135+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T17:54:32.173+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_text_dag.send_currency_rate scheduled__2024-11-05T12:00:00+00:00 [queued]>
[2024-11-06T17:54:32.192+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_text_dag.send_currency_rate scheduled__2024-11-05T12:00:00+00:00 [queued]>
[2024-11-06T17:54:32.195+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-06T17:54:32.221+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): send_currency_rate> on 2024-11-05 12:00:00+00:00
[2024-11-06T17:54:32.238+0300] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-06T17:54:32.241+0300] {standard_task_runner.py:72} INFO - Started process 96 to run task
[2024-11-06T17:54:32.240+0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'telegram_text_dag', 'send_currency_rate', 'scheduled__2024-11-05T12:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/textMessageTG-dag.py', '--cfg-path', '/tmp/tmp6mdnesmb']
[2024-11-06T17:54:32.243+0300] {standard_task_runner.py:105} INFO - Job 186: Subtask send_currency_rate
[2024-11-06T17:54:32.331+0300] {task_command.py:467} INFO - Running <TaskInstance: telegram_text_dag.send_currency_rate scheduled__2024-11-05T12:00:00+00:00 [running]> on host 1168f67a661e
[2024-11-06T17:54:32.518+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='telegram_text_dag' AIRFLOW_CTX_TASK_ID='send_currency_rate' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-05T12:00:00+00:00'
[2024-11-06T17:54:32.520+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-06T17:54:32.522+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-06T17:54:32.523+0300] {logging_mixin.py:190} INFO - Current task name:send_currency_rate state:running start_date:2024-11-06 14:54:32.176119+00:00
[2024-11-06T17:54:32.524+0300] {logging_mixin.py:190} INFO - Dag name:telegram_text_dag and current dag run status:running
[2024-11-06T17:54:32.525+0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T17:54:35.132+0300] {python.py:240} INFO - Done. Returned value was: None
[2024-11-06T17:54:35.153+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T17:54:35.155+0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=telegram_text_dag, task_id=send_currency_rate, run_id=scheduled__2024-11-05T12:00:00+00:00, execution_date=20241105T120000, start_date=20241106T145432, end_date=20241106T145435
[2024-11-06T17:54:35.158+0300] {taskinstance.py:1563} INFO - Executing callback at index 0: task_success_callback
[2024-11-06T17:54:35.161+0300] {baseoperator.py:405} WARNING - TelegramOperator.execute cannot be called outside TaskInstance!
[2024-11-06T17:54:35.172+0300] {base.py:84} INFO - Retrieving connection 'telegram_notifier'
[2024-11-06T17:54:35.784+0300] {_client.py:1773} INFO - HTTP Request: POST https://api.telegram.org/bot7997662746:AAF5-dAcYJmpsa1Pe5cqSENUoRV5D2lj5NA/sendMessage "HTTP/1.1 200 OK"
[2024-11-06T17:54:35.823+0300] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-06T17:54:35.823+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-06T17:54:35.824+0300] {logging_mixin.py:190} INFO - Dag name:telegram_text_dag queued_at:2024-11-06 14:54:26.680145+00:00
[2024-11-06T17:54:35.826+0300] {logging_mixin.py:190} INFO - Task hostname:1168f67a661e operator:PythonOperator
[2024-11-06T17:54:35.842+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-06T17:54:35.860+0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-06T17:54:35.863+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
