[2024-11-06T01:50:44.447+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T01:50:44.483+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_text_dag.send_currency_rate manual__2024-11-05T22:50:42.277794+00:00 [queued]>
[2024-11-06T01:50:44.501+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_text_dag.send_currency_rate manual__2024-11-05T22:50:42.277794+00:00 [queued]>
[2024-11-06T01:50:44.503+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-06T01:50:44.530+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): send_currency_rate> on 2024-11-05 22:50:42.277794+00:00
[2024-11-06T01:50:44.543+0300] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=68) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-06T01:50:44.545+0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'telegram_text_dag', 'send_currency_rate', 'manual__2024-11-05T22:50:42.277794+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/textMessageTG-dag.py', '--cfg-path', '/tmp/tmp9p6uf36l']
[2024-11-06T01:50:44.547+0300] {standard_task_runner.py:72} INFO - Started process 70 to run task
[2024-11-06T01:50:44.548+0300] {standard_task_runner.py:105} INFO - Job 165: Subtask send_currency_rate
[2024-11-06T01:50:44.601+0300] {task_command.py:467} INFO - Running <TaskInstance: telegram_text_dag.send_currency_rate manual__2024-11-05T22:50:42.277794+00:00 [running]> on host 1168f67a661e
[2024-11-06T01:50:44.665+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='telegram_text_dag' AIRFLOW_CTX_TASK_ID='send_currency_rate' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T22:50:42.277794+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T22:50:42.277794+00:00'
[2024-11-06T01:50:44.667+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-06T01:50:44.672+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-06T01:50:44.674+0300] {logging_mixin.py:190} INFO - Current task name:send_currency_rate state:running start_date:2024-11-05 22:50:44.485520+00:00
[2024-11-06T01:50:44.675+0300] {logging_mixin.py:190} INFO - Dag name:telegram_text_dag and current dag run status:running
[2024-11-06T01:50:44.689+0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T01:50:44.989+0300] {python.py:240} INFO - Done. Returned value was: None
[2024-11-06T01:50:45.016+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T01:50:45.017+0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=telegram_text_dag, task_id=send_currency_rate, run_id=manual__2024-11-05T22:50:42.277794+00:00, execution_date=20241105T225042, start_date=20241105T225044, end_date=20241105T225045
[2024-11-06T01:50:45.019+0300] {taskinstance.py:1563} INFO - Executing callback at index 0: task_success_callback
[2024-11-06T01:50:45.021+0300] {baseoperator.py:405} WARNING - TelegramOperator.execute cannot be called outside TaskInstance!
[2024-11-06T01:50:45.030+0300] {base.py:84} INFO - Retrieving connection 'telegram_notifier'
[2024-11-06T01:50:45.351+0300] {_client.py:1773} INFO - HTTP Request: POST https://api.telegram.org/bot7997662746:AAF5-dAcYJmpsa1Pe5cqSENUoRV5D2lj5NA/sendMessage "HTTP/1.1 200 OK"
[2024-11-06T01:50:45.398+0300] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-06T01:50:45.400+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-06T01:50:45.402+0300] {logging_mixin.py:190} INFO - Dag name:telegram_text_dag queued_at:2024-11-05 22:50:42.306078+00:00
[2024-11-06T01:50:45.404+0300] {logging_mixin.py:190} INFO - Task hostname:1168f67a661e operator:PythonOperator
[2024-11-06T01:50:45.454+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-06T01:50:45.480+0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-06T01:50:45.489+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
