[2024-11-06T01:51:46.246+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-06T01:51:46.259+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telegram_text_dag.send_currency_rate manual__2024-11-05T22:51:43.673391+00:00 [queued]>
[2024-11-06T01:51:46.266+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telegram_text_dag.send_currency_rate manual__2024-11-05T22:51:43.673391+00:00 [queued]>
[2024-11-06T01:51:46.267+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-06T01:51:46.278+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): send_currency_rate> on 2024-11-05 22:51:43.673391+00:00
[2024-11-06T01:51:46.284+0300] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-06T01:51:46.286+0300] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'telegram_text_dag', 'send_currency_rate', 'manual__2024-11-05T22:51:43.673391+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/textMessageTG-dag.py', '--cfg-path', '/tmp/tmpddg0h5_5']
[2024-11-06T01:51:46.287+0300] {standard_task_runner.py:72} INFO - Started process 90 to run task
[2024-11-06T01:51:46.288+0300] {standard_task_runner.py:105} INFO - Job 166: Subtask send_currency_rate
[2024-11-06T01:51:46.338+0300] {task_command.py:467} INFO - Running <TaskInstance: telegram_text_dag.send_currency_rate manual__2024-11-05T22:51:43.673391+00:00 [running]> on host 1168f67a661e
[2024-11-06T01:51:46.465+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='telegram_text_dag' AIRFLOW_CTX_TASK_ID='send_currency_rate' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T22:51:43.673391+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T22:51:43.673391+00:00'
[2024-11-06T01:51:46.467+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-06T01:51:46.468+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-06T01:51:46.469+0300] {logging_mixin.py:190} INFO - Current task name:send_currency_rate state:running start_date:2024-11-05 22:51:46.260762+00:00
[2024-11-06T01:51:46.470+0300] {logging_mixin.py:190} INFO - Dag name:telegram_text_dag and current dag run status:running
[2024-11-06T01:51:46.470+0300] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-06T01:51:46.701+0300] {python.py:240} INFO - Done. Returned value was: None
[2024-11-06T01:51:46.730+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-06T01:51:46.732+0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=telegram_text_dag, task_id=send_currency_rate, run_id=manual__2024-11-05T22:51:43.673391+00:00, execution_date=20241105T225143, start_date=20241105T225146, end_date=20241105T225146
[2024-11-06T01:51:46.734+0300] {taskinstance.py:1563} INFO - Executing callback at index 0: task_success_callback
[2024-11-06T01:51:46.737+0300] {baseoperator.py:405} WARNING - TelegramOperator.execute cannot be called outside TaskInstance!
[2024-11-06T01:51:46.749+0300] {base.py:84} INFO - Retrieving connection 'telegram_notifier'
[2024-11-06T01:51:47.016+0300] {_client.py:1773} INFO - HTTP Request: POST https://api.telegram.org/bot7997662746:AAF5-dAcYJmpsa1Pe5cqSENUoRV5D2lj5NA/sendMessage "HTTP/1.1 200 OK"
[2024-11-06T01:51:47.059+0300] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-06T01:51:47.060+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-06T01:51:47.062+0300] {logging_mixin.py:190} INFO - Dag name:telegram_text_dag queued_at:2024-11-05 22:51:43.693617+00:00
[2024-11-06T01:51:47.063+0300] {logging_mixin.py:190} INFO - Task hostname:1168f67a661e operator:PythonOperator
[2024-11-06T01:51:47.071+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-06T01:51:47.084+0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-06T01:51:47.088+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
