[2024-11-01T12:49:13.271+0000] {processor.py:186} INFO - Started process (PID=47) to work on /opt/airflow/dags/telegram2-dag.py
[2024-11-01T12:49:13.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/telegram2-dag.py for tasks to queue
[2024-11-01T12:49:13.276+0000] {logging_mixin.py:190} INFO - [2024-11-01T12:49:13.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/telegram2-dag.py
[2024-11-01T12:49:13.317+0000] {logging_mixin.py:190} INFO - [2024-11-01T12:49:13.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/telegram2-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/telegram2-dag.py", line 4, in <module>
    from airflow.providers.telegram.operators.telegram import TelegramOperator
ModuleNotFoundError: No module named 'airflow.providers.telegram'
[2024-11-01T12:49:13.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/telegram2-dag.py
[2024-11-01T12:49:13.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/telegram2-dag.py took 0.089 seconds
